project:
  type: book

jupyter: coq
execute: 
  cache: true
book:
  downloads: pdf
  title: "SoSe 26 Type Theory & Logic & Functional Programming Notes"
  author: "Igor Dimitrov"
  date: "4/21/2026"
  chapters:
    - index.qmd
    # - intro.qmd
    # - summary.qmd
    # - 00-notation.qmd
    - part: Logic
      chapters: 
        - 01.qmd
        - 02.qmd
        # - 03.qmd
        - 03-BooleanValues.qmd
        - 04-PropFormulas.qmd
    - references.qmd
    - resources.qmd

bibliography: references.bib
crossref: 
  chapters: true
number-depth: 1

format:
  html:
    theme:
      - cosmo
      - brand
    include-in-header: 
      - mathjax-macros.html
    css: styles.css
    code-block-bg: true
    code-copy: true
    code-overflow: wrap
    toc-depth: 4
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
    syntax-highlighting: github



